package cn.xeblog.commons.enums;

/**
 * 狗狗宇宙个人数据动作。
 */
public enum PetAction {
    ADOPT,
    RENAME,
    FEED,
    GREET_ALL_DOGS,
    WALK_DOG,
    CHECKIN,
    MAKEUP_CHECKIN,
    BUY_SLOT,
    SET_COMPANION,
    SHOP_BUY,
    SHOP_REFRESH,
    SELL_ITEM,
    SELL_COLLECTION,
    EXPLORE_START,
    EXPLORE_OPEN,
    EXPLORE_CANCEL,
    RESOLVE_OLD_TENNIS_BALL,
    TRAINING_LEARN,
    TRAINING_UPGRADE,
    TRAINING_EQUIP,
    USE_ITEM,
    RACE_RESULT,
    DAILY_SAYING_GET,
    DAILY_SAYING_READ,
    PET_PROFILE
}
